# Generated by Django 2.1 on 2018-10-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_stablishment', models.IntegerField()),
                ('mode_of_admission', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rank', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='college.list'),
        ),
    ]
